In [2]:
import numpy as np
from scipy import linalg as la

### Initializing variables

In [3]:
matrix_a = np.array([[0, 3, -1],
                     [-1, 4, -2],
                     [1, 3, 1]])
matrix_b = np.array([[2, -1, 2],
                     [-1, 0, 1],
                     [-1, 2, 2]])

vector_v = np.array([2, -1, 4])
vector_u = np.array([-2, 1, 5])

scalar_a = -2
scalar_b = 1

#### Question 1

In [4]:
# Calculating ‖𝑣‖1𝑣 + 𝑎𝑢

In [5]:
result = la.norm(vector_v, 1) * vector_v + scalar_a * vector_u
print('Result = ', result)

Result =  [18. -9. 18.]


#### Question 2

In [6]:
# Calculating the cos_theta between u and v

In [7]:
cosine_thetha = (vector_u.dot(vector_v)) / (la.norm(vector_u, 2) * la.norm(vector_v, 2))
print('Cosine of Theta between vector u and vector v = ', round(cosine_thetha, 4))

Cosine of Theta between vector u and vector v =  0.5976


#### Question 3

In [8]:
# Calculating 𝑎(𝑨∙𝑣)

In [9]:
result = scalar_a * (matrix_a.dot(vector_v))
print('Result = ', result) 

Result =  [14 28 -6]


#### Question 4

In [10]:
# Calculating 𝑨∙𝑩𝑇 + 𝑡𝑟(𝑩) ∗ 𝑳

In [11]:
matrix_b_transpose = matrix_b.T
trace_of_matrix_b = matrix_b.trace()
lower_triangular_b = la.tril(matrix_b)

result = matrix_a.dot(matrix_b_transpose) + trace_of_matrix_b * lower_triangular_b
print('Result = \n', result)

Result = 
 [[  3  -1   4]
 [-14  -1   5]
 [ -3   8  15]]


In [12]:
a = np.array([[1, 2, 3], [2, 5, 11], [3, 11, 35]])

In [14]:
sum = 0
for i in range (1, 6):
    sum += (0.5**i + 2**i)
    print(0.5**i, 2**i)

0.5 2
0.25 4
0.125 8
0.0625 16
0.03125 32


In [40]:
import operator as op
from functools import reduce

def ncr(n, r):
    r = min(r, n-r)
    numer = reduce(op.mul, range(n, n-r, -1), 1)
    denom = reduce(op.mul, range(1, r+1), 1)
    return numer // denom  # or / in Python 2

res = 0
for i in range(1, 700):
    # res += ncr(700, i) * (((1/5)**(700-i + 1) * (4/5)**(i-1) + (1/5)**(i-1) * (4/5)**(700-i + 1)))
    res +=i * (((1/5)**(700-i + 1) * (4/5) + (1/5) * (4/5)**(700-i + 1)))
    # print(i)
    
print(res)

472.7500000000002


In [ ]:
print(res