In [1]:
import numpy as np

#### Question1

In [2]:
A = np.array([[1, 0], [0, 1], [1, 1]])
B = np.array([-1, 1, 0])

In [3]:
AT_A = np.matmul(A.T, A)
print(AT_A)

[[2 1]
 [1 2]]


In [4]:
inv_AT_A = np.linalg.inv(AT_A)
print(inv_AT_A)

[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


In [5]:
x = np.matmul(np.matmul(inv_AT_A, A.T), B)
print(x, x.shape)

[-1.  1.] (2,)


In [27]:
AT_A = np.array([[2, 1],[0, 4]])
# AT_A = np.matmul(AT_A, AT_A)

In [28]:
print(np.linalg.eig(AT_A))
print(AT_A)

(array([2., 4.]), array([[1.        , 0.4472136 ],
       [0.        , 0.89442719]]))
[[2 1]
 [0 4]]


In [29]:
print(np.all(np.linalg.eigvals(AT_A) > 0))

True


In [30]:
a = np.array([[4, 0, -2], [2, 5, 4], [0,0,5]])
print(a)

[[ 4  0 -2]
 [ 2  5  4]
 [ 0  0  5]]


In [32]:
print(np.linalg.eig(a))

(array([5., 4., 5.]), array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]]))
